### ISSUE TITLE
What is is? Что это?

### ISSUE THREAD

**Issue by BabajZ** [AlexIIL/NetworkDrainCleaner#1]
Что это? What is it?

**Comment by AlexIIL** [comment]
Work in progress network debugging mod for QuiltMC-based modded minecraft. Only affects dedicated server <-> client connections at the moment, (so not singleplayer) . Must be installed on both ends to work - and this breaks networking completely if either end is missing it.

(I just updated the description to include this)

**Comment by BabajZ** [comment]
If u want u can join into my project, (minecraft anarchy utility mod) Ill sell it for 20 bucks, in dev team now 3 developers.
Dm me in discord uuid12fd;apsuvwqv124;sd[asvk1ofn#4203 
I will be very glad to see you with us

**Comment by AlexIIL** [comment]
I'm not interested in developing cheat clients.
